#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for src/backend/raft
#
# IDENTIFICATION
#    src/backend/raft/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/raft
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = pg_raft.o

include $(top_srcdir)/src/backend/common.mk
